Add e2e tests for archiveTeamsCmdF
mattermost/mmctl pull request #223
Opened 2020-10-04 08:19 UTC by shihanng

Close #15671.

2020-10-04 08:19 UTC, mattermod commented
Hello @shihanng,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-10 14:38 UTC, mgdelacroix requested changes
Looking really good @shihanng!! Added a couple of comments to add checks related to the final database status

2020-10-10 14:38 UTC, mgdelacroix commented on commands/team_e2e_test.go
> +	})
We should retrieve the team from the database using `s.th.App` and assert that after the command's execution it is now archived. After that, the team should be unarchived so the rest of the tests start from the right state.

I'm thinking on something like:

```go
basicTeam, err := s.th.App.GetTeam(s.th.BasicTeam.Id)
s.Require().Nil(err)
s.Require().NonZero(basicTeam.DeleteAt)

err := s.th.App.RestoreTeam(s.th.BasicTeam.Id)
s.Require().Nil(err)
```

2020-10-10 14:38 UTC, mgdelacroix commented on commands/team_e2e_test.go
> +	})
Same here, could you please add a check to fetch the team from the database and assert that it is not archived?

2020-10-10 23:45 UTC, shihanng commented
@mgdelacroix , thank you for the reviews. I've addressed the comments.

2020-10-14 14:13 UTC, mgdelacroix approved these changes
LGTM! :rocket: thanks for your contribution @shihanng!!

2020-10-14 16:25 UTC, ethervoid approved these changes
LGTM! Thank you for your contribution!

2020-10-15 09:16 UTC, lindy65 approved these changes
Thanks @shihanng @mgdelacroix - looks good to me 👍

2020-10-15 09:18 UTC, merged