[MM-29561] Added e2e tests to the "listCommandCmdF
mattermost/mmctl pull request #252
Opened 2020-10-18 15:04 UTC by SezalAgrawal

#### Summary

Added e2e tests to the "listCommandCmdF" mmctl command

#### Ticket Link

Fixes: mattermost/mattermost-server#15939

JIRA: https://mattermost.atlassian.net/browse/MM-29561

2020-10-18 15:04 UTC, mattermod commented
Hello @SezalAgrawal,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-20 10:23 UTC, streamer45 requested changes
Thank you for your contribution @SezalAgrawal :+1: 
I'd suggest adding a couple more test cases:

- One to trigger a permission error (listing commands on a team the user doesn't have access to).
- One where we don't pass any team as argument and expect commands for all available teams to be listed.

2020-10-20 10:31 UTC, SezalAgrawal commented
Thanks @streamer45 for your suggestions. I will add these test cases.

2020-10-21 18:43 UTC, SezalAgrawal commented
@streamer45 I have added the test cases.

2020-10-22 06:57 UTC, streamer45 approved these changes
Thank you @SezalAgrawal . Looks great :+1:

2020-10-22 10:13 UTC, lindy65 approved these changes
Thanks @SezalAgrawal - looks good to me 👍

2020-10-26 13:50 UTC, mgdelacroix requested changes
Looking really good @SezalAgrawal! Requested a couple of minor changes to include more users in the existing test cases

2020-10-26 13:50 UTC, mgdelacroix commented on commands/command_e2e_test.go
> +	s.Run("List all commands from all teams", func() {
This test case should run for both local mode and sysadmin. You can leave this `s.Run` untouched, set up the teams and commands inside and at the end, create an `s.RunForSystemAdminAndLocal` to perform the search with both users with the generated teams

2020-10-26 13:50 UTC, mgdelacroix commented on commands/command_e2e_test.go
> +	s.RunForSystemAdminAndLocal("List commands for a non existing team", func(c client.Client) {
This test case should run for all clients

```suggestion
	s.RunForAllClients("List commands for a non existing team", func(c client.Client) {
```

2020-10-26 13:50 UTC, mgdelacroix commented on commands/command_e2e_test.go
> +		s.Len(printer.GetErrorLines(), 0)
This bit should be wrapped in the `s.RunForSysadminAndLocal`

2020-10-26 15:04 UTC, SezalAgrawal commented
Thanks @mgdelacroix for your inputs! I will make the necessary changes.

2020-10-27 07:20 UTC, SezalAgrawal commented
@mgdelacroix I have updated the test cases.

2020-10-27 08:29 UTC, mgdelacroix approved these changes
Thanks @SezalAgrawal for applying the changes! LGTM! :sparkles:

2020-10-27 08:59 UTC, merged