MM-29969: add e2e test to pluginAddCmdF command
mattermost/mmctl pull request #277
Opened 2020-11-02 00:07 UTC by jecepeda

#### Summary

This PR adds tests to pluginAddCmdF command.
Cases covered:
 - Config doesn't allow plugin upload
 - Config allowed: admin and local user can upload plugin. Normal user can't

#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-29969
- https://github.com/mattermost/mattermost-server/issues/16074

### Concerns

- In order to get the example plugin I had to use the environment variable `MM_SERVER_PATH`. Is that the correct way? Using `./path_to_the_file` didn't work for me.

2020-11-02 12:00 UTC, hanzei commented
/check-cla

2020-11-06 14:50 UTC, isacikgoz approved these changes
LGTM, Have some minor comments. Thanks for the contribution @jecepeda 🚀🎉

2020-11-06 14:50 UTC, isacikgoz commented on commands/plugin_e2e_test.go
> +		printer.Clean()
Nit: We can have an empty line after this one, for the consistency.

2020-11-06 14:50 UTC, isacikgoz commented on commands/plugin_e2e_test.go
> +		})
We can do this with a `defer`.

2020-11-06 14:50 UTC, isacikgoz commented on commands/plugin_e2e_test.go
> +		})
Same as above.

2020-11-09 18:30 UTC, mgdelacroix requested changes
Thanks for the contribution @jecepeda!! It's looking really good, added only one change request not to have the plugin file in the repo, taking advantage of the one we have in the `mattermost-sever` repository

2020-11-09 18:30 UTC, mgdelacroix commented on commands/plugin_e2e_test.go
> +	fmt.Println(pluginPath)
We can directly use the `testplugin` file that exists in the server repository and not add it to `mmctl`:

```suggestion
	pluginPath := filepath.Join(os.Getenv("MM_SERVER_PATH"), "tests", "testplugin.tar.gz")
```

2020-11-09 18:30 UTC, mgdelacroix commented on commands/plugin_e2e_test.go
> +
nit: unnecessary empty line

2020-11-16 10:47 UTC, mgdelacroix approved these changes
LGTM! Thanks for applying the changes @jecepeda!

2020-11-16 18:00 UTC, isacikgoz approved these changes
Awesome!

2020-11-17 07:47 UTC, lindy65 approved these changes
Thanks @jecepeda @isacikgoz - looks good to me 👍

2020-11-28 01:02 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-28 01:04 UTC, merged