[MM-43444] Log profile image deletion issues from server
mattermost/mmctl pull request #508
Opened 2022-04-22 16:57 UTC by plant99

#### Summary

This change logs if there were issues while deleting profile image of a user when permanently deleting the account, so the admin can take manual steps.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/19996
Jira: https://mattermost.atlassian.net/browse/MM-43444

2022-04-22 16:57 UTC, mattermod commented
Hello @plant99,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-04-28 16:35 UTC, mkraft requested changes
Could you please add a test to commands/user_test.go that mocks the case of a 202 status and then ensure that you get the expected warning printed?

2022-04-28 16:35 UTC, mkraft commented on commands/user.go
> +			}
I don't think we need `deleteUser`, so if you want to you could probably do...

```diff
diff --git a/commands/user.go b/commands/user.go
index 186060c0..33877f03 100644
--- a/commands/user.go
+++ b/commands/user.go
@@ -628,10 +628,6 @@ func resetUserMfaCmdF(c client.Client, cmd *cobra.Command, args []string) error
 	return nil
 }
 
-func deleteUser(c client.Client, user *model.User) (*model.Response, error) {
-	return c.PermanentDeleteUser(user.Id)
-}
-
 func deleteUsersCmdF(c client.Client, cmd *cobra.Command, args []string) error {
 	confirmFlag, _ := cmd.Flags().GetBool("confirm")
 	if !confirmFlag {
@@ -649,7 +645,7 @@ func deleteUsersCmdF(c client.Client, cmd *cobra.Command, args []string) error {
 			printer.PrintError("Unable to find user '" + args[i] + "'")
 			continue
 		}
-		if res, err := deleteUser(c, user); err != nil {
+		if res, err := c.PermanentDeleteUser(user.Id); err != nil {
 			printer.PrintError("Unable to delete user '" + user.Username + "' error: " + err.Error())
 		} else {
 			// res.StatusCode is checked for 202 to identify issues with file deletion.
```

0/5 if you want to.

2022-06-09 13:00 UTC, mkraft approved these changes

2022-08-22 11:24 UTC, plant99 commented
/update-branch

2022-08-22 11:58 UTC, plant99 commented
Hi @mgdelacroix gentle ping to review this. I'm sure it might have slipped out of your notice since it's been a while, and is of less priority. :)

2022-08-24 20:16 UTC, mgdelacroix approved these changes
LGTM! :+1: Apologies for the delay on the review!

2022-08-24 20:16 UTC, merged

2022-08-25 06:00 UTC, plant99 commented
> LGTM! 👍 Apologies for the delay on the review!

No worries at all, thanks a lot \o/