refact: adding error handling for assignUsersCmdF
mattermost/mmctl pull request #561
Opened 2022-10-06 11:43 UTC by rafaelrubbioli

#### Summary
I added error handling for one error that was not being returned at the end of the function.

#### Ticket Link

fixes https://github.com/mattermost/mattermost-server/issues/21208

Somethings to note:
1. Ive noticed that on E2E tests there is a MM-TXXX, what is that? should I add one of those to my test?
2. I kept the printer error to stderr, this could result in duplicate errors, should it be removed?

2022-10-06 11:43 UTC, mattermod commented
Hello @rafaelrubbioli,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-06 13:33 UTC, noxer approved these changes
Thank you for your contribution. Looks good to me.

2022-10-11 13:22 UTC, isacikgoz approved these changes
LGTM, thanks for the contribution @rafaelrubbioli 🎉

2022-10-11 13:24 UTC, isacikgoz requested changes
Uh sorry, I realized that tests are failing on `e2e` tests. Can you update the tests accordingly?

2022-10-13 12:34 UTC, rafaelrubbioli commented
@isacikgoz sorry, I didn't notice it either! I think I fixed it now!

2022-10-18 15:09 UTC, noxer commented
The tests are passing now.

2022-10-19 10:06 UTC, isacikgoz approved these changes

2022-10-19 10:07 UTC, merged