ref: return multi error
mattermost/mmctl pull request #566
Opened 2022-10-07 03:02 UTC by s4kh

#### Summary
Returns multi error instead of printing and returning nil

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21211

2022-10-07 03:03 UTC, mattermod commented
Hello @s4kh,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-07 03:11 UTC, s4kh commented
@isacikgoz when we use `multierror.Append` -> the incoming error is the following:
```
actual  : "1 error occurred:\n\t* unable to find channel 'teamId:channel1'\n\n"
```
Isn't this kind of getting hard to test?

2022-10-11 12:26 UTC, isacikgoz requested changes
Hey @s4kh this looks good to me in general. Thanks for the contribution!! Could you address my comments?

2022-10-11 12:26 UTC, isacikgoz commented on commands/channel.go
> +			result = multierror.Append(result, fmt.Errorf("unable to delete channel '%s' error: %v", channel.Name, err))
```suggestion
			result = multierror.Append(result, fmt.Errorf("unable to delete channel %q: %w", channel.Name, err))
```

2022-10-11 19:51 UTC, s4kh commented
> Hey @s4kh this looks good to me in general. Thanks for the contribution!! Could you address my comments?

@isacikgoz Addressed the requested changes.

2022-10-12 12:14 UTC, isacikgoz reviewed
Looks good, just a small nit, it's good to go after that. Thanks @s4kh

2022-10-12 12:14 UTC, isacikgoz commented on commands/channel_test.go
> +		// s.Require().EqualError(err, fmt.Sprintf("unable to find channel '%s'", arg))
Can you remove the commented out code?

2022-10-14 08:35 UTC, isacikgoz approved these changes
Thanks for the contribution @s4kh Looks good to me!

2022-10-17 09:36 UTC, noxer approved these changes

2022-10-17 09:38 UTC, noxer commented
/e2e-test

2022-10-17 09:38 UTC, mattermod commented
Failed to get the PR information required to trigger testing. Please retry later.

2022-10-17 10:34 UTC, noxer commented
/e2e-test

2022-10-17 10:34 UTC, mattermod commented
Failed to get the PR information required to trigger testing. Please retry later.

2022-10-17 12:28 UTC, noxer commented
Ran the test manually, all good.

2022-10-17 12:28 UTC, merged