[GH-21210] refactor(commands): add error handling to listCommandCmdF
mattermost/mmctl pull request #569
Opened 2022-10-08 15:56 UTC by VictorAssunc

#### Summary
Added error handling in `listCommandCmdF` for errors that were only printed and not returned.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21210

2022-10-08 15:56 UTC, mattermod commented
Hello @VictorAssunc,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-19 10:50 UTC, isacikgoz reviewed
Looks good in general, @VictorAssunc can you address the linter issue?

2022-10-20 17:11 UTC, VictorAssunc commented
> 

for sure, i will work on it

2022-10-21 12:03 UTC, VictorAssunc commented
done ♻️

2022-11-01 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-11-01 08:52 UTC, noxer requested changes
Great work! One small change request from me and we are good to go.

2022-11-01 08:52 UTC, noxer commented on commands/command.go
> +			errs = multierror.Append(errs, fmt.Errorf("unable to list commands for '%s'", team.Id))
```suggestion
			errs = multierror.Append(errs, fmt.Errorf("unable to list commands for '%s': %w", team.Id, err))
```
We should add the original error here.

2022-11-15 01:56 UTC, VictorAssunc commented
♻️

2022-11-15 13:53 UTC, noxer approved these changes
Looks good, thank you very much @VictorAssunc.

2022-11-22 19:32 UTC, isacikgoz approved these changes

2022-11-22 19:33 UTC, merged