mmctl: Review unarchiveChannelsCmdF function to return an error in case of a failure #21212
mattermost/mmctl pull request #572
Opened 2022-10-10 08:16 UTC by KiptoonKipkurui

#### Summary

#### Ticket Link

This pull request addresses Help Wanted ticket https://github.com/mattermost/mattermost-server/issues/21212
The current function returns nil error if an error occurs and only prints the error output to the screen. This pull request remedies that by returning an aggregate error using (multiError)[https://github.com/hashicorp/go-multierror]

2022-10-10 08:16 UTC, mattermod commented
Hello @KiptoonKipkurui,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-10-10 08:27 UTC, KiptoonKipkurui commented
/check-cla

2022-10-19 09:14 UTC, isacikgoz requested changes
Thanks for the contribution @KiptoonKipkurui there is a small bug in the code that needs to be addressed.

2022-10-19 09:14 UTC, isacikgoz commented on commands/channel.go
> +			partialError := fmt.Sprintf("Unable to find channel '" + args[i] + "'")
`channels` and `args` are not correlated with indexes, you can't use `args[i]` to find channel names. The `args` are separated with a whitspace whereas channels are separated with a colon (`:`).

2022-10-19 10:48 UTC, isacikgoz commented on commands/channel.go
> +			result = multierror.Append(result, errors.New(partialError))
```suggestion
			err := fmt.Errorf("unable to find channel %q", args[i])
			printer.PrintError(err.Error())
			result = multierror.Append(result, err)
```

2022-10-19 10:48 UTC, isacikgoz commented on commands/channel.go
> +	var result error
Can you use `multierror.Error` here? To maintain the consistency.

2022-10-19 10:48 UTC, isacikgoz commented on commands/channel.go
> +	return result
If we use `*multierror.Error`, we can do:
```suggestion
	return result.ErrorOrNil()
```

2022-10-19 11:03 UTC, KiptoonKipkurui commented
@isacikgoz let me make the changes

2022-10-20 14:48 UTC, KiptoonKipkurui commented
@isacikgoz what is your linting format for go so that i can address the failing test?

2022-10-21 12:38 UTC, noxer requested changes
Thank you for your contribution @KiptoonKipkurui, just two small issues from my side.

2022-10-21 12:38 UTC, noxer commented on commands/channel.go
> +			err := fmt.Errorf("Unable to find channel '%s'", args[i])
```
Error: ST1005: error strings should not be capitalized (stylecheck)
```

2022-10-21 12:38 UTC, noxer commented on commands/channel.go
> +			restoreError := fmt.Sprintf("Unable to unarchive channel '" + args[i] + "'. Error: " + err.Error())
You can directly create this as a `fmt.Errorf`, this will also trigger `Error: ST1005: error strings should not be capitalized (stylecheck)`.

2022-11-01 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-11-01 08:45 UTC, noxer requested changes
Thank you for the fixes @KiptoonKipkurui. I've requested an additional change (they are all the same, don't worry). Sorry for the slow review process, we've got a lot of PRs to get through.

2022-11-01 08:45 UTC, noxer commented on commands/channel_e2e_test.go
> +		s.Require().NotNil(err)
Please use `s.Require().Error(err)` for this. It makes the error messages easier to interpret should the test fail at some point.

2022-11-01 08:45 UTC, noxer commented on commands/channel_e2e_test.go
> +		s.Require().NotNil(err)
See above

2022-11-01 08:45 UTC, noxer commented on commands/channel_e2e_test.go
> +		s.Require().NotNil(err)
See above

2022-11-01 08:45 UTC, noxer commented on commands/channel_test.go
> +		s.Require().NotNil(err)
See above

2022-11-01 08:45 UTC, noxer commented on commands/channel_test.go
> +		s.Require().NotNil(err)
See above

2022-11-01 08:45 UTC, noxer commented on commands/channel_test.go
> +		s.Require().NotNil(err)
See above

2022-11-01 08:45 UTC, noxer commented on commands/channel_test.go
> +		s.Require().NotNil(err)
See above

2022-11-01 08:45 UTC, noxer commented on commands/channel_test.go
> +		s.Require().NotNil(err)
See above

2022-11-04 05:35 UTC, KiptoonKipkurui commented on commands/channel_test.go
> +		s.Require().NotNil(err)
Done

2022-11-05 19:42 UTC, KiptoonKipkurui commented
@noxer Hi, any help with improving failing code coverage tests?

2022-11-07 09:38 UTC, noxer commented
/update-branch

2022-11-07 10:12 UTC, KiptoonKipkurui commented
@noxer any tips to remedy the failing code coverage tests?

2022-11-09 16:36 UTC, KiptoonKipkurui commented
@isacikgoz @lurcio Hi, sorry to ask this over and over but I have a failing test that pertains to the code coverage tests. The same test on the current master (without my contribution) branch fails. How can I help improve this coverage to enable complete tests?

2022-11-09 16:50 UTC, noxer commented
Sorry for the late response. I'm not sure why it is failing. I'll investigate further.

2022-11-20 01:04 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-11-22 12:20 UTC, noxer commented
/update-branch

2022-11-22 19:34 UTC, isacikgoz commented
/update-branch

2022-11-22 19:52 UTC, isacikgoz commented
From the tests seems like a capitalization issue. @KiptoonKipkurui please do assertions for error messages.

2022-12-03 01:05 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-08-08 11:29 UTC, hanzei commented
Thank you for your contribution. :+1:  `mmctl` has been moved into https://github.com/mattermost/mattermost/tree/master/server/cmd/mmctl.  Please resubmit your PR to https://github.com/mattermost/mattermost.

2023-08-08 11:29 UTC, closed without merging