Issue 21219: improve error handling for botDisableCmdF
mattermost/mmctl pull request #576
Opened 2022-10-14 05:03 UTC by ariyonaty

#### Summary

Error handling for the `botDisableCmdF` function updated to return an error in case of failure. 
Update includes the use of `multiError.Error` for appending all errors and returning error if one occurs.

#### Ticket Link

2022-10-14 05:03 UTC, mattermod commented
Hello @ariyonaty,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-18 14:23 UTC, noxer commented
Hi @ariyonaty, thank you for your contribution. I'll run some tests and review the code.

2022-10-19 08:57 UTC, isacikgoz approved these changes
Awesome, LGTM 🎉

2022-10-28 08:47 UTC, noxer requested changes
Looks good, a few small change requests from my side.

2022-10-28 08:47 UTC, noxer commented on commands/bot.go
> +			result = multierror.Append(result, fmt.Errorf("can't find user '%v'", args[i]))
Please use `%q` to quote strings, the original code was lacking in that regard as well. It would be awesome if you could change it there as well.

2022-10-28 08:47 UTC, noxer commented on commands/bot.go
> +			result = multierror.Append(result, fmt.Errorf("could not disable bot '%v'", args[i]))
Could you please add the `err` to the message?

2022-10-28 08:47 UTC, noxer commented on commands/bot_e2e_test.go
> +		s.Require().NotNil(err)
Please check for errors using `s.Require().Error(err)`, it makes the messages more readable.

2022-10-28 08:47 UTC, noxer commented on commands/bot_e2e_test.go
> +		s.Require().NotNil(err)
Same as above

2022-10-28 18:58 UTC, ariyonaty commented
@noxer - Thank you for the feedback.
Addressed the comments in commit [6daf6bd](https://github.com/mattermost/mmctl/pull/576/commits/6daf6bd525b95a8d78e8b17a77dcf7ff6021d14f).

2022-11-09 01:04 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-11-09 09:28 UTC, noxer approved these changes
Perfect, thank you @ariyonaty :1st_place_medal:

2022-11-09 09:28 UTC, merged