Issue 21220: improve error handling for botEnableCmdF function
mattermost/mmctl pull request #577
Opened 2022-10-14 05:06 UTC by ariyonaty

#### Summary

Error handling for the `botEnableCmdF` function updated to return an error in case of failure. 
Update includes the use of `multierror.Error` for appending all errors and returning error if one occurs.

#### Ticket Link

2022-10-14 05:06 UTC, mattermod commented
Hello @ariyonaty,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-19 08:56 UTC, isacikgoz approved these changes
Thanks for the contribution @ariyonaty LGTM!

2022-10-28 08:29 UTC, noxer requested changes
Hi @ariyonaty, thank you very much for your contribution. I've got a few requests but otherwise it looks good.

2022-10-28 08:29 UTC, noxer commented on commands/bot.go
> +			result = multierror.Append(result, fmt.Errorf("can't find user '%v'", args[i]))
Please use `%q` to quote strings
```suggestion
			result = multierror.Append(result, fmt.Errorf("can't find user %q", args[i]))
```

2022-10-28 08:29 UTC, noxer commented on commands/bot.go
> +			result = multierror.Append(result, fmt.Errorf("could not enable bot '%v'", args[i]))
Same here. Please also include the error with `%w`.
```suggestion
			result = multierror.Append(result, fmt.Errorf("could not enable bot %q: %w", args[i], err))
```

2022-10-28 08:29 UTC, noxer commented on commands/bot_e2e_test.go
> +		s.Require().NotNil(err)
Please check this with `s.Require().Error(err)`, it makes the test messages much easier to read.

2022-10-28 08:29 UTC, noxer commented on commands/bot_e2e_test.go
> +		s.Require().NotNil(err)
Same as above

2022-10-28 08:42 UTC, noxer commented
Hey @ariyonaty, do you have questions about the proposed changes?

2022-10-28 18:58 UTC, ariyonaty commented
@noxer - Appreciate the feedback.  
Addressed the comments in commit [5c1a6fb](https://github.com/mattermost/mmctl/pull/577/commits/5c1a6fbf5af85b37574df6ccdafc72750e1f37ec).

2022-11-09 01:04 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-11-09 09:26 UTC, noxer approved these changes
Looks good, thank you very much @ariyonaty. :rocket:

2022-11-09 09:26 UTC, merged