fix:modifyTeamsCmd
mattermost/mmctl pull request #583
Opened 2022-10-21 16:53 UTC by arshad-k7

#### Summary

#### Ticket Link

2022-10-24 18:26 UTC, noxer requested changes
Thank you very much for your contribution @arshad-k7. I'd like to request a few changes. Could you also please update the tests, so they check for the error. You can find the tests in `commands/team_test.go`.

2022-10-24 18:26 UTC, noxer commented on commands/team.go
> +	var Error error
```suggestion
	var errors *multierror.Error
```
We generally avoid upper case variable names in Go. In this case we want to collect the errors in a `*multierror.Error`.

2022-10-24 18:26 UTC, noxer commented on commands/team.go
> +			Error = multierror.Append(Error, fmt.Errorf("Unable to find team '" + args[i] + "'"))
```suggestion
			Error = multierror.Append(Error, fmt.Errorf("Unable to find team %q", args[i]))
```
You can use a placeholder to put the argument into the error. Most function in `fmt` that end in `f` can do this (`Printf`, `Errorf`, `Sprintf`, etc).

2022-10-24 18:26 UTC, noxer commented on commands/team.go
> +			Error = multierror.Append(Error, fmt.Errorf("Unable to modify team '" + team.Name + "' error: " + err.Error()))
Same as above, you can wrap errors with `%w`, which is specific for `fmt.Errorf`.

2022-10-24 18:26 UTC, noxer commented on commands/team.go
> +	return Error
After the change to `*multierror.Error`, you need to call `errors.ErrorOrNil()` to return an `error` here.

2022-11-04 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-11-22 19:36 UTC, isacikgoz commented
@arshad-k7 Let us know if you need any further guidance to address what @noxer pointed out. It's okay if you can't find some time to work on this. Just keep us posted.

2023-03-27 13:49 UTC, isacikgoz commented
Closing this PR due to inactivity. Thanks for your efforts so far @arshad-k7!

2023-03-27 13:49 UTC, closed without merging