[MM-47823] SendPasswordResetEmailCmdF command error handle refactoring
mattermost/mmctl pull request #586
Opened 2022-10-22 10:33 UTC by misantron

#### Summary

SendPasswordResetEmailCmdF command error handle refactoring and tests update

#### Ticket Link

Issue: https://github.com/mattermost/mattermost-server/issues/21463
JIRA: https://mattermost.atlassian.net/browse/MM-47823

2022-10-22 10:33 UTC, mattermod commented
Hello @misantron,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-24 17:41 UTC, noxer requested changes
Hi @misantron, thank you very much for your contribution. I'd like to request a few small changes. Also the linter complains about a few issues. Other than that it looks good.

2022-10-24 17:41 UTC, noxer commented on commands/user_test.go
> +		s.Require().NotNil(err)
`EqualError` already checks this, no need check for `NotNil`.

2022-10-24 17:41 UTC, noxer commented on commands/user_test.go
> +		s.Require().NotNil(err)
Same as above

2022-10-24 17:41 UTC, noxer commented on commands/user_test.go
> +		s.Require().NotNil(err)
Same as before

2022-10-24 17:41 UTC, noxer commented on commands/user.go
> +			result = multierror.Append(result, errors.Errorf("Invalid email '%s'", email))
Please use `fmt.Errorf` here. Also the error message should not be capitalized.

2022-10-24 18:38 UTC, noxer requested changes
Thanks for the changes, looks good. One small nitpick from me.

2022-10-24 18:38 UTC, noxer commented on commands/user.go
> +			result = multierror.Append(result, fmt.Errorf("unable send reset password email to email %s. Error: %v", email, err))
You can use `%w` to wrap the error.

2022-10-24 19:12 UTC, noxer approved these changes
Awesome, thank you very much!

2022-10-28 07:58 UTC, isacikgoz approved these changes
LGTM! Thanks for the contribution and adding new test cases @misantron 🚀

2022-10-28 07:58 UTC, isacikgoz commented
/update-branch

2022-10-28 08:18 UTC, noxer commented
@misantron A recent change from another PR added the import, the merge lead to duplicate imports. Could you remove those, please?

2022-10-28 11:20 UTC, isacikgoz approved these changes
Thanks for fixing the import issue, we need to work on the CI as this should've been flagged before merging the upstream.

2022-10-28 11:20 UTC, merged