Refactored resetUserMfaCmdF to return multierror
mattermost/mmctl pull request #598
Opened 2022-10-25 11:23 UTC by AntiGhot

#### Summary
Returns multi error instead of printing and returning nil

make build  // success
make test   // success
make test-e2e // success

#### Ticket Link

github : https://github.com/mattermost/mattermost-server/issues/21467
JIRA: https://mattermost.atlassian.net/browse/MM-47819

2022-10-25 11:23 UTC, mattermod commented
Hello @AntiGhot,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-26 19:53 UTC, AntiGhot commented
@isacikgoz

2022-10-27 10:32 UTC, noxer requested changes
Hi @AntiGhot, thank you very much for your contribution. I'd like to request one change. Otherwise the PR looks good.

2022-10-27 10:32 UTC, noxer commented on commands/user.go
> +			result = multierror.Append(result, fmt.Errorf("Unable to reset user '"+user.Id+"' MFA. Error: "+err.Error()))
You can use string interpolation here:
```suggestion
			result = multierror.Append(result, fmt.Errorf("Unable to reset user %q MFA. Error: %w", user.Id, err))
```

2022-10-27 16:22 UTC, AntiGhot commented
@noxer review comments addressed

2022-10-28 06:39 UTC, isacikgoz approved these changes
Thanks @AntiGhot LGTM 💙

2022-10-28 08:24 UTC, noxer approved these changes
Yes, perfect. Thank you @AntiGhot

2022-10-28 08:24 UTC, merged