refact: removeAllUsersFromChannel to return an error
mattermost/mmctl pull request #599
Opened 2022-10-27 08:30 UTC by moogacs

#### Summary
refactor removeAllUsersFromChannel to feedback the error on return instead of just printing

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-47341
Issue: https://github.com/mattermost/mattermost-server/issues/21218

2022-10-27 08:30 UTC, mattermod commented
Hello @moogacs,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-10-27 08:30 UTC, moogacs commented
/check-cla

2022-10-27 08:33 UTC, moogacs commented
/check-cla

2022-11-15 01:04 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-11-17 07:16 UTC, noxer requested changes
Thank you very much for your contribution, @moogacs. I'd like to request a few changes and there seem to be linter errors to fix (a simple `go fmt` should take care of those).

2022-11-17 09:54 UTC, moogacs commented on commands/channel_users.go
> +		return errors.Errorf("Unable to remove all users from " + channel.Name + ". Error: " + err.Error())
good catch, just followed what was there :D

2022-11-18 10:38 UTC, noxer approved these changes
Thank you very much for your contribution @moogacs.
The PR looks good. I've added a nit but feel free to ignore it, it's not that important.

2022-11-18 10:38 UTC, noxer commented on commands/channel_users_test.go
> +		s.Require().NotNil(err)
This check is unnecessary, the error will be checked in the next line anyway.

2022-11-18 10:45 UTC, isacikgoz approved these changes
LGTM, thanks @moogacs 🎉 good to merge after what @noxer pointed out.

2022-11-18 11:26 UTC, merged