Adding restoreTeamsCmdF function to return an error in case of a failure
mattermost/mmctl pull request #601
Opened 2022-10-28 18:16 UTC by sonalimahajan12

#### Summary

#### Ticket Link

2022-10-28 18:16 UTC, mattermod commented
Hello @sonalimahajan12,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-10-28 18:19 UTC, sonalimahajan12 commented
@isacikgoz Can you please assign this issue to me & review this as well.

2022-10-29 14:31 UTC, dsharma522 commented
Not sure, how there are duplicate issues for the same thing. 
I have already worked on this and opened a PR https://github.com/mattermost/mmctl/pull/581

2022-10-29 14:32 UTC, dsharma522 commented
@isacikgoz  , looks like it is duplicate issue

2022-11-04 16:40 UTC, noxer requested changes
Hi @sonalimahajan12 and thank you for your contribution. I'd like to request one small change.

2022-11-04 16:40 UTC, noxer commented on commands/team.go
> +			teamErr := fmt.Errorf("Unable to find team '" + args[i] + "'")
You can use string interpolation here
```suggestion
			teamErr := fmt.Errorf("Unable to find team %q", args[i]")
```
using `%q` will automatically add `"` around the string.

2022-11-04 16:48 UTC, noxer commented
Duplicate of #581. Please make sure that you are assigned the original ticket first before working on it.

2022-11-04 16:48 UTC, closed without merging