[MM-47812] Refactor addUserToTeam function to return an error
mattermost/mmctl pull request #603
Opened 2022-10-29 17:36 UTC by svbnbyrk

#### Summary
Added multi-error handling for teamUsersAddCmdF func.

#### Ticket Link
Issue: mattermost/mattermost-server/issues/21474
Jira: https://mattermost.atlassian.net/browse/MM-47812

2022-10-29 17:36 UTC, mattermod commented
Hello @svbnbyrk,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-10-29 17:41 UTC, svbnbyrk commented
/check-cla

2022-10-31 10:37 UTC, noxer requested changes
Thank you very much for your contribution @svbnbyrk. There are a few issues with the code formatting and I've suggested a small change in the test code. Otherwise this looks good.

2022-10-31 10:37 UTC, noxer commented on commands/team_users_e2e_test.go
> +		s.Require().NotNil(err)
You can check this with `s.Require().Error(err)`, which makes the test messages easier to read.

2022-10-31 10:37 UTC, noxer commented on commands/team_users_e2e_test.go
> +		s.Require().ErrorContainsf(err, "can't find user '%s'",nonexistentUserEmail)
The file is not `gofmt`'d, the linter will complain.

2022-10-31 10:37 UTC, noxer commented on commands/team_users_e2e_test.go
> +		s.Require().NotNil(err)
Use `Error` here

2022-10-31 10:37 UTC, noxer commented on commands/team_users_test.go
> +		s.Require().NotNil(err)
... and here

2022-10-31 12:06 UTC, svbnbyrk commented
Hi @noxer, I resolved all conversations.

2022-11-06 19:28 UTC, svbnbyrk commented
I didn't get any unit test, e2e test or lint errors. It seems ok.

2022-11-07 12:07 UTC, svbnbyrk commented
/update-branch

2022-11-07 13:09 UTC, svbnbyrk reviewed
Ok.

2022-11-08 10:30 UTC, noxer approved these changes
Thank you very much for your contribution @svbnbyrk. I've added Ibrahim as the second reviewer. We'll merge it as soon as he approves.

2022-11-08 15:05 UTC, merged