[MM-47811]: improve error handling for removeUserFromTeam function
mattermost/mmctl pull request #616
Opened 2022-11-23 18:44 UTC by hionay

#### Summary

Error handling for the `removeUserFromTeam` function updated to return an error in case of failure.
Update includes the use of `multierror.Error` for appending all errors and returning error if one occurs for the function `teamUsersRemoveCmdF`.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/21475

2022-11-23 18:48 UTC, hionay commented
/check-cla

2022-11-23 18:57 UTC, hionay commented
/check-cla

2022-12-02 15:38 UTC, noxer requested changes
Hi @hionay, thank you very much for your contribution. I'd like to request a few changes. Otherwise this looks good.

2022-12-02 15:38 UTC, noxer commented on commands/team_users.go
> +		err := errors.Errorf("can't find user '%s'", userArg)
Could you use `fmt.Errorf` here, please? We're moving away from `pkg/errors`.

2022-12-02 15:38 UTC, noxer commented on commands/team_users_test.go
> +		s.Require().NotNil(err)
You can use `s.Require().Error(err)` here. That makes the error messages easier to understand.

2022-12-02 15:38 UTC, noxer commented on commands/team_users_test.go
> +		s.Require().NotNil(err)
Same here

2022-12-02 17:16 UTC, noxer approved these changes
Looks good to me, thank you very much @hionay. I'll added Ibrahim as a second reviewer and then this PR is ready to merge.

2022-12-07 16:25 UTC, isacikgoz approved these changes
LGTM, thanks @hionay 🚀

2022-12-07 16:25 UTC, merged